#!/usr/bin/env sh
# Terminate already running bar instances
_ps=(swaybg mako waybar polkit-gnome network-traffic.sh)
for _prs in "${_ps[@]}"; do
         if [[ `pidof ${_prs}` ]]; then
                 killall -9 ${_prs}
         fi
done
while pgrep -x waybar >/dev/null; do sleep 1; done
~/.azotebg &
mako &
polkit-gnome &
waybar -c $HOME/.config/sway/waybar/config.json -s $HOME/.config/sway/waybar/style.css &
pactl set-sink-volume @DEFAULT_SINK@ 70%
